@include('contact-points._section', [
    'owner' => $relation,
    'ownerType' => 'person_organization_relation',
    'contactPoints' => $relation->contactPoints,
    'storeRoute' => $contactPointsStoreRoute,
    'destroyRouteName' => 'contact-points.destroy',
    'contactTypes' => $contactTypes,
    'contactUsages' => $contactUsages,
    'formIdPrefix' => 'relation-contact-point-' . $relation->id,
    'collapseId' => 'relation-contact-point-create-' . $relation->id,
    'errorBag' => 'storeRelationContactPoint',
    'createLabel' => 'Nuovo recapito',
    'sectionTitle' => 'Recapiti della relazione',
    'modal' => false,
    'renderModals' => false,
])